### ISSUE TITLE
A Heartfelt Thank You and a Question About Future Updates ❤️

### ISSUE THREAD

**Issue by wAnFen1017** [Banz99/Final-Fantasy-Type-0-Hd-Unlocker#19]
Hi @Banz99 ,

I hope this message finds you well!

First of all, I want to express my deepest gratitude for creating this mod. Final Fantasy Type-0 HD holds a special place in my heart—it’s a game I first played when I was 14, and now, 10 years later, it still brings back incredible memories. Thanks to your mod, I’ve been able to relive those moments with stunning visuals and smooth gameplay. The work you’ve done has truly transformed the experience for players like me, and I can’t thank you enough for that. 🙏

I noticed that the last update was in 2022, and I completely understand how life and other projects can take priority. I just wanted to check in and see if you’re considering any future updates for the mod. I know the community around this game is small, but your efforts have made a huge impact on all of us.

If there’s anything I can do to help or contribute, please let me know! I’d love to support your work however I can.

Thank you once again for everything you’ve done. Your dedication and passion have brought joy to so many of us. Wishing you all the best, and I hope to hear from you soon!

Warm regards,
@wAnFen1017

**Comment by Banz99** [comment]
Thanks for the kind words, I appreciate them.
The state of this project is left as is for a couple of reasons, as you said some other things took over, but more importantly, after having spent hundreds of hours testing various possible workarounds, I came to the conclusion that with my current knowledge I can simply do no better than what was provided back then. This game was made to run @ 30 fps at the core and there are tons of assumptions in the code around that, and more than once fixing something somewhere meant breaking something else elsewhere, and given that I really can't do a playthrough of everything everytime I change a small thing. As much as I'd rather not admit it, even if I had the actual source code available instead of a pseudo reconstruction via decompilers, it would be quite the task to fix everything for higher framerates (or even better, actually allowing for dynamic framerates without slowdowns), so I don't blame Hexadrive for not going that route given the testing that there would have been needed behind. As for how one could contribute if he was to "pick up the torch", they'd need to know modern x86 assembly quite well (which I know is not a simple requirement) and memory searches through Cheat Engine and the like, then they'd need to undrm the latest exe on steam via [SteamLess](https://github.com/atom0s/Steamless) and finally do static analysis with a disassembler/decompiler like IDA/Ghidra, I rewrote the patching process in the latest commit available to be more "comprehensible", and even planned a semi tutorial on how to do it, but since noone ever expressed interest in it I kinda pushed that aside. Being a complicated subject for a niche game well past its release and relevance time doesn't really help my chances.

**Comment by wAnFen1017** [comment]
Thanks so much for the detailed response. Honestly, after hearing about all the challenges you faced, I have even more appreciation for everything you’ve accomplished. The fact that you managed to push the game as far as you did—despite all the limitations baked into its core—is seriously impressive.

It’s a real bummer that the code is so rigid with the 30 FPS limit and all the assumptions tied to it. I can imagine how exhausting it must’ve been to tweak something, only to have it break something else in some random corner of the game. It’s a tough spot to be in, and I totally understand why things are where they are now.

Just wanted to say thanks again for all the time and effort you put into this project. You’ve given fans like me an incredible experience, and that means a lot.🙌

Take care!
